name: wbc_counter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_charts: ^0.5.1
  pie_chart: ^5.3.2
  share: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/cells/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "#673AB7"
  adaptive_icon_foreground: "assets/icon_logo.png"
  adaptive_icon_mask: true
  
  web:
    generate: true
    image_path: "assets/icon_logo.png"
    background_color: "#673AB7"
    theme_color: "#673AB7"
  windows:
    generate: true
    image_path: "assets/icon_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon_logo.png"