# @format

name: wbc_counter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_charts: ^0.5.1
  pie_chart: ^5.3.2
  share: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.2
  url_launcher: ^6.1.14
  permission_handler: ^11.0.0
  #DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  uuid: ^4.2.2
  pix_flutter: ^2.2.0
  in_app_review: ^2.0.8
  intl: ^0.18.1
  country_code_picker: ^3.0.0
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/cells/

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "#673AB7"
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_mask: true
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#673AB7"
    theme_color: "#673AB7"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"

# dart run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true
  web: true
  background_image: "assets/background.png"
  image: "assets/icon.png"
  color: "#673AB7"
  color_dark: "#673AB7"
  background_image_dark: "assets/background.png"
  image_dark: "assets/icon.png"

  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

  fullscreen: true
  android12: true
  android_12:
    splash_color: "#673AB7"
    splash_color_dark: "#673AB7"
flutter_intl:
  enabled: true
